# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-04 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=20)),
                ('category_name', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=200)),
                ('product1', models.CharField(max_length=20)),
                ('product2', models.CharField(max_length=20)),
                ('product3', models.CharField(max_length=20)),
                ('sort', models.IntegerField()),
            ],
            options={
                'db_table': 'maindescriptions',
                'ordering': ['sort'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='child_cid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifics',
            field=models.CharField(max_length=20),
        ),
    ]
