# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-05 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.CharField(max_length=20)),
                ('child_name', models.CharField(max_length=40)),
                ('sort', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Categorie')),
            ],
            options={
                'db_table': 'childcategories',
                'ordering': ['sort'],
            },
        ),
    ]
