# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0004_childcategorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('phoneNum', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tokenValue', models.CharField(max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('lastTime', models.DateTimeField(auto_now=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
